---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/quotes":
    get:
      summary: Gets the quotes
      parameters:
      - name: token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: quotes retrieved
          content: {}
        '401':
          description: unauthorized
          content: {}
  "/api/v1/quotes/{id}":
    get:
      summary: Gets a quote
      parameters:
      - name: token
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: int
      responses:
        '200':
          description: quote retrieved
          content: {}
        '404':
          description: quote not found
          content: {}
  "/api/v1/users":
    post:
      summary: Creates an api token
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: blank email
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
              required:
              - email
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
